---
language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t karras/flatpak .

script:
  - docker run --privileged -it karras/flatpak /bin/sh -c "git clone https://github.com/karras/flatpak-xchat /root/flatpak-xchat; flatpak-builder build /root/flatpak-xchat/io.github.Xchat.json"
